### PR TITLE
Feature/recombine enumerated zip sequence

### PR DESCRIPTION
**Pull request by mgovers**
Resolve comments from knowledge sharing session:

* `++` and `--` instead of `+= 1` and `-= 1`
* zip-like loop over both `sources` and `load_gens` instead of two loops

@TonyXiang8787 I did a benchmark on (Clang CL) release build comparing `main` and this branch and it appears that `main` is almost consistently better. See also the benchmark outputs in [benchmark.zip](https://github.com/PowerGridModel/power-grid-model/files/13111445/benchmark.zip). My guess is that the zipped loop actually introduces more cache misses because there are more variables in the output. Maybe you can try to reproduce this? I think it would be a shame to replace efficient code by something that is less efficient, but I don't want to block this change if we cannot reproduce the regression

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@mgovers can you do a benchmark on gcc/clang in Linux?

**Comment by mgovers** [comment]
> @mgovers can you do a benchmark on gcc/clang in Linux?

This looks more like it (but keep in mind that this is on WSL, which is a virtual machine, not a native one) [benchmark_wsl.zip](https://github.com/PowerGridModel/power-grid-model/files/13111669/benchmark_wsl.zip)

Just for the sake of completeness, here's also the benchmark for MSVC, which also looks comparable: [benchmark_msvc.zip](https://github.com/PowerGridModel/power-grid-model/files/13111688/benchmark_msvc.zip)

**Comment by TonyXiang8787** [comment]
@mgovers it seems in Linux the benchmark results are comparable between main and this feature. So we could conclude the performance impact is minimal.

It is very interesting to see in WSL clang has significant performance improvements than gcc.

**Comment by TonyXiang8787** [comment]
@mgovers Another observation about current benchmark target. We are compiling it with address sanitizer enabled, which can have significant performance slow-down.

**Comment by mgovers** [comment]
> @mgovers Another observation about current benchmark target. We are compiling it with address sanitizer enabled, which can have significant performance slow-down.

hmm good point. do i need to re-run the benchmarks without address sanitizer? and do we need to overwrite the compiler flags for the benchmark target?

**Comment by TonyXiang8787** [comment]
> > @mgovers Another observation about current benchmark target. We are compiling it with address sanitizer enabled, which can have significant performance slow-down.
> 
> hmm good point. do i need to re-run the benchmarks without address sanitizer? and do we need to overwrite the compiler flags for the benchmark target?

Yes, use clang/gcc in Linux/WSL as the main judgement. After disabling address-sanitizer, if the performance benchmark does not differ very much, merge this PR as is. If `main` is significantly faster (>10%), we need to talk about it.

**Comment by mgovers** [comment]
new benchmark results:

[benchmark_wsl.zip](https://github.com/PowerGridModel/power-grid-model/files/13165759/benchmark_wsl.zip)

**Comment by mgovers** [comment]
i guess if we only compare the fasted runs for the same compiler then the results are comparable

**Review by TonyXiang8787 — APPROVED** [review]

**Pull request merged**
