### PR TITLE
[Hotfix] fix restore after failing batch scenario

### PR DESCRIPTION
**Pull request by mgovers**
**Fixes issue**: #461 

### Changes proposed in this PR include:

This is a hotfix that does not care about performance.

Approprate sustainable solution will be done in #460 .

### CODE REVIEW

**Comment by mgovers** [comment]
Failing CI is due to boost artifactory bug https://github.com/boostorg/boost/issues/844

**Review by TonyXiang8787 — APPROVED** [review]
Approved.

Just to be sure on the reasoning. Because we do not need to worry about performance for error scenario, so we choose to copy the model (less efficient), other than try to restore the components (more complicated).

**Comment by mgovers** [comment]
> Approved.
> 
> Just to be sure on the reasoning. Because we do not need to worry about performance for error scenario, so we choose to copy the model (less efficient), other than try to restore the components (more complicated).

yes indeed. In the near future, a sustainable solution will improve on this. Since this is a hotfix, fixing functionality is more important than performance

**Comment by mgovers** [comment]
> Failing CI is due to boost artifactory bug [boostorg/boost#842](https://github.com/boostorg/boost/issues/842)

re-running after https://github.com/TonyXiang8787/pybuild-header-dependency/pull/3 fixed the boost URL

**Pull request merged**
