### PR TITLE
Release/v1.10.x

### PR DESCRIPTION
**Pull request by mgovers**
Bump version to v1.10.x

Requires

* [x] #787 
* [x] #811 
* [x] #822 

Solves (but not closes) #803

### CODE REVIEW

**Comment by figueroa1395** [comment]
> Solves (but not closes) #803

Why doesn't it close it?

Also, let's add to the todo list:

- [ ] Update full change log in #803 after the above are merged.

**Comment by mgovers** [comment]
Windows benchmark using MSVC Release with the `power_grid_model_benchmark_cpp` build target looks reasonably comparable

[benchmark-msvc-v1-9-0.txt](https://github.com/user-attachments/files/17678449/benchmark-msvc-v1-9-0.txt)
[benchmark-msvc-v1-9-86.txt](https://github.com/user-attachments/files/17678450/benchmark-msvc-v1-9-86.txt)
[benchmark-msvc-v1-10-rc.txt](https://github.com/user-attachments/files/17678451/benchmark-msvc-v1-10-rc.txt)

**Comment by figueroa1395** [comment]
Benchmark on Ubuntu 22.04 on WSL2 using g++-12 Release. The results look comparable as well.
[benchmark-g++12-v1-9-0.txt](https://github.com/user-attachments/files/17679219/benchmark-g%2B%2B12-v1-9-0.txt)
[benchmark-g++-12-v1-9-86.txt](https://github.com/user-attachments/files/17679220/benchmark-g%2B%2B-12-v1-9-86.txt)
[benchmark-g++-12-v1-10-rc.txt](https://github.com/user-attachments/files/17679221/benchmark-g%2B%2B-12-v1-10-rc.txt)

**Comment by mgovers** [comment]
Nightly running in https://github.com/PowerGridModel/power-grid-model/actions/runs/11745484947

**Comment by TonyXiang8787** [comment]
@mgovers sonar-cloud was skipped due to a old and not-needed logic. I have fixed this in #[5e16d13](https://github.com/PowerGridModel/power-grid-model/pull/823/commits/5e16d134d3dd11287669ba24b4fd9c6c3478cafe).

Now I put the PR in ready-for-review, feel free to drag it into the merge queue on Monday.

**Review by figueroa1395 — APPROVED** [review]

**Pull request merged**
