### PR TITLE
Move PGM workshop examples

### PR DESCRIPTION
**Pull request by Laurynas-Jagutis**
Related to https://alliander.atlassian.net/browse/DNR-1985?atlOrigin=eyJpIjoiYzVlNmM3MDU5YjY0NDdiZWFlNmYxZGE3NmMyYzQwZDgiLCJwIjoiaiJ9

Moving examples from PGM workshop to main PGM repository and making sure that they run. Some more details are in the ticket.

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
Hi @Laurynas-Jagutis, about the folder structure

1. Put all example notebooks in the `docs` folder, not in de root.
2. We do not need any `.csv` data file, they are not needed in the examples.
3. You can put the `json` files in the `docs/examples/data` folder.

**Comment by Laurynas-Jagutis** [comment]
In "Serialization Example.ipynb" third cell we wanted to extract dataset_type by using ```dataset, dataset_type = json_deserialize(data)``` However, there appears to be an error: **ValueError: too many values to unpack (expected 2)** indicating that we expected a tuple but we didnt get one. Instead we get ```Dict[str, ndarray | Dict[str, ndarray]]```. 

How important is it to demonstrate how to extract the data_type? Since if I change the line to ```dataset = json_deserialize(data)``` and leave the data_type out, then the whole notebook works fine.

What is more, if the tuple method is outdated, I will also have to change several docstrings.

**Comment by TonyXiang8787** [comment]
> In "Serialization Example.ipynb" third cell we wanted to extract dataset_type by using `dataset, dataset_type = json_deserialize(data)` However, there appears to be an error: **ValueError: too many values to unpack (expected 2)** indicating that we expected a tuple but we didnt get one. Instead we get `Dict[str, ndarray | Dict[str, ndarray]]`.
> 
> How important is it to demonstrate how to extract the data_type? Since if I change the line to `dataset = json_deserialize(data)` and leave the data_type out, then the whole notebook works fine.
> 
> What is more, if the tuple method is outdated, I will also have to change several docstrings.
> 
> By the way, my findings on the internet suggest that it is impossible to properly review jupyter notebooks without third party programs. Is that true?

The API has been changed in between. Your new code is good:  `dataset = json_deserialize(data)`

**Comment by TonyXiang8787** [comment]
@Laurynas-Jagutis it is indeed not possible to review the difference of Jupyter Notebook in GitHub. As far as I know they are working on a new feature for this.

**Comment by TonyXiang8787** [comment]
@Laurynas-Jagutis You need to add serialization examples in the index here:

https://github.com/PowerGridModel/power-grid-model/blob/8030beb8c395bb5622253c19c7b70ed33f8939ff/docs/index.md?plain=1#L78

**Comment by TonyXiang8787** [comment]
@Laurynas-Jagutis several comments for your PR

1. For serialization notebook, create a new chapter to demo dump and load `msgpack` format. Explain that will be more efficient than `json`.
2. For make test dataset notebook, remove the content of the chapter `JSON Data Format`. We do not need to explain it again since it is already explained in serialization documentation. You just put a link to the serialization doc markdown and serialization example notebook in this chapter.

**Pull request merged**
