### PR TITLE
[FEATURE] migrate to miniforge

### PR DESCRIPTION
**Pull request by mgovers**
Do not use miniconda but use miniforge instead

## logs or it didn't happen

the logs are quite difficult to interpret but it is clear that `miniforge` is installed to `/runners/miniconda3/` which is interesting but i guess to the best of our effort

before: taken from https://github.com/PowerGridModel/power-grid-model/actions/runs/8896817941/job/24430327994
after: taken from https://github.com/PowerGridModel/power-grid-model/actions/runs/8909980841/job/24468327997
[logs.zip](https://github.com/PowerGridModel/power-grid-model/files/15177560/logs.zip)

### CODE REVIEW

**Review by TonyXiang8787 — APPROVED** [review]

**Comment by mgovers** [comment]
@TonyXiang8787 should we delete the main channels?

```
            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by TonyXiang8787** [comment]
> @TonyXiang8787 should we delete the main channels?
> 
> ```
>             channel URLs : https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
> ```

`miniforge` only use `conda-forge` channel.

**Comment by mgovers** [comment]
> > @TonyXiang8787 should we delete the main channels?
> > ```
> >             channel URLs : https://conda.anaconda.org/conda-forge/linux-64
> >                           https://conda.anaconda.org/conda-forge/noarch
> >                           https://repo.anaconda.com/pkgs/main/linux-64
> >                           https://repo.anaconda.com/pkgs/main/noarch
> >                           https://repo.anaconda.com/pkgs/r/linux-64
> >                           https://repo.anaconda.com/pkgs/r/noarch
> > ```
> 
> `miniforge` only use `conda-forge` channel.

yes but i got those logs from the CI on this branch

**Review by TonyXiang8787 — CHANGES_REQUESTED** [review]
By looking at logs you are still using `miniconda`.

**Comment by TonyXiang8787** [comment]
> > By looking at logs you are still using `miniconda`.
> 
> * I have no way to verify. It installs `miniforge` to the directory `miniconda3`, potentially because the github action is called `miniconda3`, even if you specify a different provider.
> * It should be possible to explicitly get rid of the default channels. Should not be too hard. Will investigate.

See my last commit

**Comment by TonyXiang8787** [comment]
https://docs.conda.io/projects/conda/en/4.6.1/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually

**Comment by mgovers** [comment]
d

> > > By looking at logs you are still using `miniconda`.
> > 
> > 
> > 
> > * I have no way to verify. It installs `miniforge` to the directory `miniconda3`, potentially because the github action is called `miniconda3`, even if you specify a different provider.
> > * It should be possible to explicitly get rid of the default channels. Should not be too hard. Will investigate.
> 
> See my last commit

doesn't seem to have worked:

```
     active environment : conda-pgm-env
    active env location : /home/runner/miniconda3/envs/conda-pgm-env
            shell level : 1
       user config file : /home/runner/.condarc
 populated config files : /home/runner/miniconda3/.condarc
                          /home/runner/.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.3.0=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/runner/miniconda3  (writable)
      conda av data dir : /home/runner/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /home/runner/miniconda3/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Linux/6.5.0-1018-azure ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1001:127
             netrc file : None
           offline mode : False
```

taken from https://github.com/PowerGridModel/power-grid-model/actions/runs/8910424346/job/24469677542?pr=584

**Comment by mgovers** [comment]
this worked @TonyXiang8787
[remove channels as whole](https://github.com/PowerGridModel/power-grid-model/pull/584/commits/aaf19b44f8d1da3f1ed5087fd516d1273d84b38e)
[aaf19b4](https://github.com/PowerGridModel/power-grid-model/pull/584/commits/aaf19b44f8d1da3f1ed5087fd516d1273d84b38e)

```
     active environment : conda-pgm-env
    active env location : /home/runner/miniconda3/envs/conda-pgm-env
            shell level : 1
       user config file : /home/runner/.condarc
 populated config files : /home/runner/miniconda3/.condarc
                          /home/runner/.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.3.0=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/runner/miniconda3  (writable)
      conda av data dir : /home/runner/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /home/runner/miniconda3/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Linux/6.5.0-1018-azure ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1001:127
             netrc file : None
           offline mode : False

```

**Comment by mgovers** [comment]
looks OK now

**Review by TonyXiang8787 — APPROVED** [review]

**Pull request merged**
