### PR TITLE
add scaling param in params.json

### PR DESCRIPTION
**Pull request by nitbharambe**
The scaling factor was missing in params

### CODE REVIEW

**Comment by mgovers** [comment]
We currently do not expose that parameter from the API so i'm not sure whether we want to add that value to this file

**Review by mgovers — CHANGES_REQUESTED** [review]
Either also add it to the C and Python APIs or don't mention it to our users at all

**Comment by TonyXiang8787** [comment]
I would propose to not to merge this PR. Until later we add the voltage scaling into the argument, we don't do it.

**Comment by mgovers** [comment]
shall I close as won't fix?

**Comment by mgovers** [comment]
The documentation includes the following lines:

> - To account for the different operational conditions, a voltage scaling factor of `c` is applied to the voltage source while running short circuit calculation function. By default, the value is considered as `1.1` in power-grid-model. 
> A detailed table for its selection is mentioned in IEC 60909.

should we update that with this design choice now or in a follow-up PR?

**Comment by TonyXiang8787** [comment]
This one should be closed. Adding a factor in the `params.json` does not make sense at this moment.

**Pull request closed without merging**
