### PR TITLE
Release v1.7.0: Newton-Raphson State Estimation

### LINKED ISSUE #237: [FEATURE] Possibility to specify different sigma's for P and Q in state estimator
Within team Insight into Loads we apply the state estimator to the MS grid. We see an issue in our output related to the restriction (if we understand correctly that this is the case) of one sigma for both the P and Q of a (pseudo-)measurement. We have the following inputs:

- MSRs (loads) containing lots of households: those will have a larger margin of uncertainty for P due to sampling of anonymous user profiles.
- MSRs containing just one large consumer (AC5): those will have a very small margin of uncertainty for P due to an available measurement
- Measurement of P and Q at the substation (afgaande velden): both P and Q have a small margin of uncertainty here.

In general, we expect a low Q for households and a possibly higher Q for the larger customers. Unfortunately, because we specify one sigma for P and Q, the reactive power is largely attributed to the households now whenever the measurement at the substation indicates that there is reactive power on the route. This makes the output of such routes/grids invalid for our application. Would it be possible to specify two different sigma's within one (pseudo-)measurement within the state estimator, so we can start influencing the attribution of Q more accurate?

### LINKED ISSUE #369: Newton-Raphson method for state estimation
Newton-Raphson method should solve the issue in #237

### PR DESCRIPTION
**Pull request by mgovers**
Closes #369
Closes #237 

* Bump version
* Make Newton-Raphson state estimation stable (instead of experimental)

* [ ] full clang-tidy run

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@mgovers also remove the deprecated import export json functions.

**Comment by mgovers** [comment]
> @mgovers also remove the deprecated import export json functions.

can we do that? i think the tests in PGM-IO still use the old function calls as a fallback. Would imply a version bump on PGM-IO as well.

I would propose to wait until #493 is implemented, no?

**Comment by TonyXiang8787** [comment]
@mgovers please do not create a release branch

**Comment by TonyXiang8787** [comment]
> > @mgovers also remove the deprecated import export json functions.
> 
> 
> 
> can we do that? i think the tests in PGM-IO still use the old function calls as a fallback. Would imply a version bump on PGM-IO as well.
> 
> 
> 
> I would propose to wait until #493 is implemented, no?

Then keep the json functions for now.

**Comment by mgovers** [comment]
> @mgovers please do not create a release branch

yeah i noticed. will recreate the PR from a different branch

**Pull request closed without merging**
