### PR TITLE
macos cross-compilation

### LINKED ISSUE #466: [BUG] ValueErrors on MacBook on >=v1.6.22
**Describe the bug**

The data types on MacBook changed in `v1.6.22`. As a result, `pandas.DataFrame` representations of the PGM output data may not be correct and/or consistent.

Further investigation will be done in pair programming session.

**Input Data Validity**

(private data)

**Data Dump**

(private data)

**To Reproduce**

```py
# (private data)
df = pd.merge(output_data, ...)
df.reindex(...)  # <- raises ValueError: cannot reindex on an axis with duplicate labels
```

**Expected behavior**

(private data)

**Additional context**

It affects MacBooks with M1 processors. It seems to be closely related to https://github.com/PowerGridModel/power-grid-model/compare/v1.6.21..v1.6.22

### PR DESCRIPTION
**Pull request by mgovers**
May fix #466 .

We can only test this after attempting to build

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@mgovers what do you want to achieve here? We cannot test macOS on arm (only cross compile) in GitHub Actions. They don't have a public M1 runner.

Can we just ask Jean to run the `pytest` in his laptop?

**Comment by mgovers** [comment]
> @mgovers what do you want to achieve here? We cannot test macOS on arm (only cross compile) in GitHub Actions. They don't have a public M1 runner.
> 
> Can we just ask Jean to run the `pytest` in his laptop?

they should have it now according to https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ but it doesn't seem to work correctly yet

In addition, we should be able to cross-compile for macos with both x86_64 and arm64 architecture according to https://cibuildwheel.readthedocs.io/en/stable/faq/#arm64

I'm just trying it out now

**Comment by mgovers** [comment]
> @mgovers what do you want to achieve here? We cannot test macOS on arm (only cross compile) in GitHub Actions. They don't have a public M1 runner. The M1 runner large is a paid service for commercial use.
> 
> Can we just ask Jean to run the `pytest` in his laptop?

i will but i've already found out yesterday that he receives all zeros as output from the PGM, which is why i strongly suspect different architectures to be the issue

**Comment by TonyXiang8787** [comment]
> > @mgovers what do you want to achieve here? We cannot test macOS on arm (only cross compile) in GitHub Actions. They don't have a public M1 runner.
> > Can we just ask Jean to run the `pytest` in his laptop?
> 
> they should have it now according to https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ but it doesn't seem to work correctly yet
> 
> In addition, we should be able to cross-compile for macos with both x86_64 and arm64 architecture according to https://cibuildwheel.readthedocs.io/en/stable/faq/#arm64
> 
> I'm just trying it out now

The M1 runner in GitHub Actions is a paid service even for open-source project.

We already do the cross compilation for a long time. In the macOS build using Intel Mac runner, we build and test `x64`, and build `arm64` but not test it.

**Comment by mgovers** [comment]
> > > @mgovers what do you want to achieve here? We cannot test macOS on arm (only cross compile) in GitHub Actions. They don't have a public M1 runner.
> > > Can we just ask Jean to run the `pytest` in his laptop?
> > 
> > 
> > they should have it now according to https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ but it doesn't seem to work correctly yet
> > In addition, we should be able to cross-compile for macos with both x86_64 and arm64 architecture according to https://cibuildwheel.readthedocs.io/en/stable/faq/#arm64
> > I'm just trying it out now
> 
> The M1 runner in GitHub Actions is a paid service even for open-source project.

Ah ok, that explains.

> We already do the cross compilation for a long time. In the macOS build using Intel Mac runner, we build and test `x64`, and build `arm64` but not test it.

i see now from the pyproject.toml indeed. Well, one way or another, everything looks like it's borked for M1 processors after this change: https://github.com/PowerGridModel/power-grid-model/compare/v1.6.21..v1.6.22 .

**Comment by TonyXiang8787** [comment]
> > We already do the cross compilation for a long time. In the macOS build using Intel Mac runner, we build and test `x64`, and build `arm64` but not test it.
> 
> i see now from the pyproject.toml indeed. Well, one way or another, everything looks like it's borked for M1 processors after this change: https://github.com/PowerGridModel/power-grid-model/compare/v1.6.21..v1.6.22 .

@Thijss Also have run `pytest` in his M3 macOS. It seems everything runs okay. @Thijss can you comment on that?

**Comment by mgovers** [comment]
unit tests + validation tests pass on Jean's MacBook. Closing this PR

**Pull request closed without merging**
