### PR TITLE
Bugfix/msvc release build slow

### PR DESCRIPTION
**Pull request by mgovers**
Split up test cases to speed up compilation time

## Benchmark (approximate)

I obtained the following benchmark (approximate order, no exact numbers). I have no reason to believe that the regressions for GCC release build are related to this change, because the python build also was slower, and [compilation of the `test_main_model.cpp`](https://github.com/PowerGridModel/power-grid-model/actions/runs/5335362271/jobs/9668491860) file took about as long as for [`main`](https://github.com/PowerGridModel/power-grid-model/actions/runs/5322936675/jobs/9642256307)

| compiler | build mode | Github actions (before) | Github actions (after) | local laptop (before) | local laptop (after) |
| -------- | ---------- | ----------------------- | ---------------------- | --------------------- | -------------------- |
| MSVC     | debug      | 7min                   | 10 min                 | 1min30s                | 1min05s              |
| MSVC     | release    | 1u12min                 | 16min                  | 50min                  | 3min30s              |
| GCC | debug | 12min | 11min | | |
| GCC | release | 29min | 34min | | |
| Clang (Linux) | debug | 6min | 8min | | |
| Clang (Linux) | release | 14min | 11min | | |  
| Clang (MacOS) | debug | 10min | 10min | | |
| Clang (MacOS) | release | 15min | 16min | | |

## Review suggestions
I recommend reviewing this in Split diff view:
image

## Taken approach

```cpp
TEST_CASE("A") { // A
  // setup code
  // Var x

  SUB_CASE("1"){ // A.1
    // setup + cases A.1
    // use(x)

    SUB_CASE("a"){ // A.1.a
      // impl A.1.a
    }
    SUB_CASE("b"){ // A.1.b
      // impl A.1.b
    }
  }
  SUB_CASE("2") { // A.2
    // impl A.2
  }
}
```

into

```cpp
namespace {
State state {
  // setup code
  Var x;
};
}

TEST_CASE("A.1"){ // A.1
  // setup + cases A.1
  // use(state.x)

  SUB_CASE("a"){ // A.1.a
    // impl A.1.a
  }
  SUB_CASE("b"){ // A.1.b
    // impl A.1.b
  }
}

TEST_CASE("A.2") { // A.2
  // impl A.2
}
```

### CODE REVIEW

**Comment by mgovers** [comment]
I ran 2 isolated Github actions runs on `windows-latest`:

* one with MSVC `19.36.32532.0` (part of VC toolset `14.36.32532`) which is default on `windows-latest` image `20230612.1` (default after start of slow MSVC release build using [01620b9](https://github.com/PowerGridModel/power-grid-model/pull/278/commits/01620b950a71fc4a0336c6a7f7f6d62a217e5bf1)
* one with MSVC `19.35.32217.1` (part of VC toolset `14.35.32215`) which was default on `windows-latest` image `20230606.1` (default prior to the first case of slow MSVC release build using [edf5b89](https://github.com/PowerGridModel/power-grid-model/pull/278/commits/edf5b8980a2f5aa8b40414e6be2f043ab17475e8)

The former was ~4x slower. The main culprit appears to be the `test_main_model.cpp` compilation step (took one hour). It is not worth investigating more, since our runners are free (due to open source) and at the cost of microsoft itself anyway. they will fix themselves.

See also:

* [This thread](https://github.com/actions/runner-images/issues/7739), including [this comment](https://github.com/actions/runner-images/issues/7739#issuecomment-1598251513). Credits to its creator for finding a workaround
* [Windows github runners images](https://github.com/actions/runner-images/releases)/tag/win22%2F20230606.1

**Comment by mgovers** [comment]
@TonyXiang8787 to answer your question: On my laptop, MSVC 19.36 (VC Toolset 14.36)

* Develop: 1m11s to do a clean rebuild (much faster than on the previous installation, I don't have numbers but I think it was a couple minutes)
* Release: it's already been running for quite a few minutes (much slower than on the previous version). i will update this when it's (finally) done

I will re-open this issue because i do not believe this is workable.

**Comment by mgovers** [comment]
@TonyXiang8787 to answer your question: On my laptop, MSVC 19.36 (VC Toolset 14.36)

* Develop: 1m11s to do a clean rebuild (much faster than on the previous installation, I don't have numbers but I think it was a couple minutes)
* Release: it's already been running for quite a few minutes (much slower than on the previous version). i will update this when it's (finally) done

I will re-open this issue because i do not believe this is workable.

**Comment by mgovers** [comment]
@TonyXiang8787 the added code smell is related to the size of the `State` struct. I did not want to change that now because that's an issue with the original code. I just moved the issue.

**Comment by TonyXiang8787** [comment]
@mgovers Is this a draft or ready?

**Comment by mgovers** [comment]
this is ready 😄

**Review by TonyXiang8787 — APPROVED** [review]

**Pull request merged**
